// Shared presentation contracts; compatibility imports retain their existing path.
export type {
	PanelActionContribution,
	PanelActionInvokeContext,
	PanelActionLocation,
	PanelActionsApi,
	PanelBadgeDefinition,
	PanelCommandActionContribution,
	PanelCommandMenuItemContribution,
	PanelContentDefinition,
	PanelControlActionContribution,
	PanelControlContribution,
	PanelControlRenderContext,
	PanelControlsApi,
	PanelHeaderDefinition,
	PanelMenuActionContribution,
	PanelMenuItemContribution,
	PanelSeparatorMenuItemContribution,
	ResolvedPanelActionState,
} from "@forgeax/app-shell/application";
